export const BLOG_COPY = {
  en: {
    blogTitle: 'Blogs',
    blogDescription: 'Blogs on positioning, offers, pipeline systems, and conversion for service-led businesses.',
    filterByCategory: 'Read by category',
    recentPosts: 'Recent posts',
    articleSingular: 'article',
    articlePlural: 'articles',
    inCategory: 'in',
    all: 'All',
    topics: 'Topics',
    featured: 'Featured',
    popular: 'Popular',
    viewAll: 'View all',
    latestInsights: 'Latest insights',
    publishedInsights: 'Published insights',
    focusAreas: 'Focus areas',
    readTime: 'min read',
    readArticle: 'Read article',
    bookCall: 'Book a call',
    toc: 'On this page',
    sections: 'Sections',
    tags: 'Tags',
    actionStep: 'Action Step',
    commonMistake: 'Common Mistake',
    endCta: 'Want this built for you? Book a strategy call.',
    backToBlog: 'Back to Blog',
    emptyTitle: 'No articles published yet',
    emptyBody: 'Published articles will appear here once they are available.',
    notFoundTitle: 'Article not found',
    notFoundBody: 'This article is not published yet or the slug is invalid.',
    categories: {
      creator: 'Creator',
      coach: 'Coach',
      consultant: 'Consultant',
      service: 'Service',
    },
  },
  ar: {
    blogTitle: 'المقالات',
    blogDescription: 'مقالات عن التموضع، والعروض، والـ pipeline، والتحويل للشركات الخدمية.',
    filterByCategory: 'اقرأ حسب التصنيف',
    recentPosts: 'أحدث المقالات',
    articleSingular: 'مقال',
    articlePlural: 'مقالات',
    inCategory: 'ضمن',
    all: 'الكل',
    topics: 'المواضيع',
    featured: 'مقال مميز',
    popular: 'الأكثر قراءة',
    viewAll: 'عرض الكل',
    latestInsights: 'أحدث المقالات',
    publishedInsights: 'مقالات منشورة',
    focusAreas: 'مجالات التركيز',
    readTime: 'دقائق قراءة',
    readArticle: 'اقرأ المقال',
    bookCall: 'احجز مكالمة',
    toc: 'محتوى المقال',
    sections: 'الأقسام',
    tags: 'الوسوم',
    actionStep: 'خطوة عملية',
    commonMistake: 'خطأ شائع',
    endCta: 'هل تريد تنفيذ هذا معك؟ احجز مكالمة استراتيجية.',
    backToBlog: 'العودة إلى المدونة',
    emptyTitle: 'لا توجد مقالات منشورة بعد',
    emptyBody: 'ستظهر المقالات هنا فور نشرها.',
    notFoundTitle: 'المقال غير موجود',
    notFoundBody: 'هذا المقال غير منشور حالياً أو أن الرابط غير صحيح.',
    categories: {
      creator: 'صانع محتوى',
      coach: 'كوتش',
      consultant: 'مستشار',
      service: 'خدمي',
    },
  },
};
