'use strict';

const cta = (label, url, style = 'primary') => ({ label, url, style, isExternal: false });
const item = (title, description, icon = '') => ({ title, description, icon });
const step = (stepTitle, deliverables, successCriteria = '', timeframe = '') => ({
  stepTitle,
  deliverables,
  successCriteria,
  timeframe,
});
const metric = (value, label, hint) => ({ value, label, hint });
const faq = (question, answer) => ({ question, answer });
const offer = (title, description, icon, url, outcome, capabilities, displayOrder) => ({
  title,
  description,
  icon,
  url,
  outcome,
  capabilities,
  ctaLabel: `Explore ${title}`,
  displayOrder,
  isActive: true,
  featuredOnHomepage: true,
});

const servicesEn = () => ({
  __component: 'blocks.service-overview',
  eyebrow: 'Active systems',
  heading: 'Systems we build',
  description:
    'We begin with the part of the system where progress is being lost.',
  placement: 'homepage',
});

const servicesAr = () => ({
  __component: 'blocks.service-overview',
  eyebrow: 'العروض المتاحة',
  heading: 'ابدأ بالنظام الذي يسبب أكبر عائق.',
  description:
    'تعمل عروضنا الحالية على جزأين عاليي القيمة: كيف تجذب الشركة الفرص وكيف تقدم قيمتها وتحول الانتباه إلى إجراء. ويمكن إضافة أنظمة أخرى بعد تطويرها والتحقق منها.',
  placement: 'homepage',
});

const englishPages = [
  {
    slug: 'home',
    title: 'Home',
    seo: {
      metaTitle: 'Injaaz Digital | Growth, Website & Onboarding Systems',
      metaDescription:
        'Connect customer acquisition, conversion-focused websites, and client onboarding into practical business systems.',
      keywords: 'customer acquisition, website development, client onboarding, business systems',
      canonicalUrl: '/',
      noIndex: false,
    },
    blocks: [
      {
        __component: 'blocks.hero',
        title: 'Build the systems that move customers from attention to delivery.',
        subtitle:
          'Injaaz Digital connects acquisition, conversion, and onboarding so serious businesses can create demand, earn trust, and begin delivery with less friction.',
        primaryCta: cta('Book a strategy call', '/book-call'),
        secondaryCta: cta('Explore the three engines', '#services', 'secondary'),
        align: 'left',
      },
      servicesEn(),
      {
        __component: 'blocks.problem',
        eyebrow: 'Disconnected work creates hidden costs',
        heading: 'A campaign, website, and workflow should not behave like separate projects.',
        description:
          'Momentum is lost when each team optimizes its own deliverable while the customer experiences one continuous journey.',
        items: [
          item('Attention without qualification', 'Campaigns can create activity while sales receives incomplete or low-fit opportunities.'),
          item('Trust without action', 'A polished website can still leave visitors unsure what to do, what happens next, or why they should act now.'),
          item('Sales without readiness', 'A signed customer can still wait days while information, documents, scheduling, and internal setup are collected manually.'),
        ],
      },
      {
        __component: 'blocks.process',
        eyebrow: 'The complete customer path',
        heading: 'Every stage should make the next stage easier.',
        description: 'Attention → Interest → Conversion → Sales → Onboarding → Delivery',
        steps: [
          step('Attention', 'Reach the right market with an offer and message built for relevance.', 'Qualified people notice the right promise.'),
          step('Interest', 'Use creative and content to make the problem, value, and next step understandable.', 'Interest becomes intentional exploration.'),
          step('Conversion', 'Turn website visits into forms, bookings, WhatsApp conversations, or other meaningful actions.', 'Intent becomes measurable action.'),
          step('Sales', 'Give the team useful context and a clear handoff for follow-up.', 'Opportunities arrive with enough information to progress.'),
          step('Onboarding', 'Collect requirements, documents, confirmations, and scheduling in one guided flow.', 'The customer knows what happens next.'),
          step('Delivery', 'Create the internal brief, project structure, ownership, and kickoff conditions.', 'The team can start with complete context.'),
        ],
      },
      {
        __component: 'blocks.final-cta',
        heading: 'Find the constraint before buying another disconnected deliverable.',
        description: 'Use a focused strategy call to identify whether growth, conversion, or onboarding should be improved first.',
        primaryCta: cta('Request a system diagnosis', '/book-call'),
        secondaryCta: cta('Explore Growth Engine', '/growth-system', 'secondary'),
      },
    ],
  },
  {
    slug: 'growth-system',
    title: 'Growth Engine',
    seo: {
      metaTitle: 'Growth Engine | Customer Acquisition & Lead Generation',
      metaDescription:
        'Build a measurable customer-acquisition system connecting offer, campaigns, landing pages, qualified leads, tracking, and optimization.',
      keywords: 'lead generation, customer acquisition, paid advertising, landing pages, marketing analytics',
      canonicalUrl: '/growth-system',
      noIndex: false,
    },
    blocks: [
      {
        __component: 'blocks.page-hero',
        title: 'Turn marketing investment into qualified business opportunities.',
        description:
          'Growth Engine connects market insight, offer strategy, creative, campaigns, landing pages, lead qualification, and KPI analysis into one measurable acquisition system.',
        primaryCta: cta('Request a Growth Diagnosis', '/book-call'),
        secondaryCta: cta('See the acquisition flow', '#process', 'secondary'),
        imageKeyword: 'customer-acquisition-system',
      },
      {
        __component: 'blocks.problem',
        eyebrow: 'Why budget gets wasted',
        heading: 'Buying ads is not the same as building an acquisition engine.',
        description:
          'When the offer, campaign, landing page, qualification, and follow-up are disconnected, reports show activity but decisions remain unclear.',
        items: [
          item('The offer is never diagnosed', 'Budget is increased before testing whether the market, promise, or audience has a compelling reason to respond.'),
          item('The campaign and page disagree', 'Clicks arrive with one expectation and meet a different message, weak trust, or unnecessary friction.'),
          item('Cheap leads become the target', 'Cost per lead falls while qualification, contact, booking, and sales opportunity rates are ignored.'),
          item('Nobody can locate the bottleneck', 'Teams cannot tell whether the constraint is audience, creative, message, page, form, or follow-up.'),
        ],
      },
      {
        __component: 'blocks.process',
        eyebrow: 'The acquisition mechanism',
        heading: 'A connected path from offer to optimization.',
        description: 'Each stage is designed and measured in relation to the next.',
        steps: [
          step('Offer', 'Clarify the market, problem, desired outcome, proof, and reason to act.', 'A relevant promise for a defined audience.'),
          step('Message', 'Translate the offer into clear campaign angles and conversion copy.', 'The right customer recognizes the value quickly.'),
          step('Creative', 'Develop static concepts, video scripts, and recording direction where useful.', 'Creative earns attention without distorting the offer.'),
          step('Campaign', 'Build the audience, channel, budget, and testing structure around the objective.', 'Spend produces interpretable learning.'),
          step('Landing page', 'Align message, trust, objections, form design, and next action.', 'Clicks become informed intent.'),
          step('Qualified lead', 'Collect the context sales needs and route it to WhatsApp, booking, CRM, or Sheets.', 'Sales receives usable opportunities.'),
          step('Optimization', 'Read performance across the journey and improve the actual constraint.', 'Decisions follow evidence, not vanity metrics.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'What can be included',
        heading: 'Built around the business model, not a fixed funnel template.',
        description:
          'The final scope depends on the offer, sales process, channel, internal capacity, and data already available.',
        items: [
          item('Market and offer analysis', 'Audience research, competitive context, offer structure, and acquisition strategy.'),
          item('Campaign system', 'Channel planning, account structure, targeting, launch, and testing priorities.'),
          item('Copy and creative direction', 'Advertising copy, concepts, video scripts, recording guidance, and static creative where applicable.'),
          item('Landing experience', 'Landing-page strategy, copy, design, responsive development, and conversion paths.'),
          item('Lead qualification', 'Forms and questions that balance completion rate with the context sales actually needs.'),
          item('Business-tool integration', 'Routing to WhatsApp, booking, CRM, Google Sheets, or another practical destination.'),
          item('Tracking and reporting', 'Conversion events, KPI definitions, dashboards, and decision-ready reporting.'),
          item('Analysis and optimization', 'Performance diagnosis and recommendations focused on the weakest stage of the journey.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'KPI intelligence',
        heading: 'Metrics become useful when their relationships explain what to fix.',
        description:
          'Reporting follows the path from reach to qualified opportunity, and extends to acquisition cost or return when reliable sales data is available.',
        items: [
          item('Attention quality', 'Impressions, reach, frequency, click-through rate, and cost per click show whether the market is responding.'),
          item('Landing behavior', 'Landing-page views, conversion rate, form starts, completion, and abandonment reveal message match and friction.'),
          item('Lead economics', 'Cost per lead matters alongside qualified-lead rate, booking rate, contact rate, and sales-qualified opportunity rate.'),
          item('Business outcomes', 'Cost per qualified opportunity, customer-acquisition cost, and return on ad spend are used when the underlying sales data is trustworthy.'),
          item('High reach, low clicks', 'Often points to audience, offer, message, or creative—not a reason to raise budget immediately.'),
          item('Strong clicks, weak conversion', 'Often signals message mismatch, insufficient trust, unclear value, or excessive landing-page friction.'),
          item('Good conversion, poor lead quality', 'Often signals weak qualification, broad targeting, or a promise attracting the wrong intent.'),
          item('Good leads, weak sales outcomes', 'May reveal slow response, weak follow-up, capacity limits, or a sales-process constraint.'),
        ],
      },
      {
        __component: 'blocks.process',
        eyebrow: 'How we work',
        heading: 'Diagnose first. Build what the evidence requires.',
        description: 'A concise cycle for launching, learning, and improving without hiding behind activity.',
        steps: [
          step('Diagnose', 'Review the market, offer, customer journey, current performance, data quality, and sales handoff.'),
          step('Design', 'Define the strategy, measurement plan, experiments, and required assets.'),
          step('Build', 'Create the campaign, creative, landing, capture, integration, and tracking components in scope.'),
          step('Launch', 'Validate the flow end to end and release with clear ownership and baseline metrics.'),
          step('Learn', 'Collect enough signal to distinguish noise from a genuine constraint.'),
          step('Optimize', 'Improve the stage most likely to increase qualified opportunities—not the easiest metric to change.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'Fit and adaptability',
        heading: 'The engine changes with how the company sells.',
        description:
          'A consultant, local service company, B2B team, real-estate business, educator, and e-commerce brand should not use the same acquisition path.',
        items: [
          item('Best for', 'Businesses with a real offer, capacity to respond, a willingness to improve, and a need for measurable acquisition.'),
          item('Consultants and agencies', 'May prioritize authority, diagnosis, qualification, booking, and a strong sales conversation.'),
          item('Local services and real estate', 'May prioritize location, urgency, phone or WhatsApp response, availability, and assignment.'),
          item('B2B and education', 'May require longer consideration, multiple stakeholders, resources, nurturing, and sales-stage visibility.'),
          item('E-commerce', 'May focus on product economics, merchandising, checkout behavior, repeat purchase, and channel contribution.'),
          item('Operational readiness', 'The company must be able to contact, qualify, and serve the additional opportunities the engine creates.'),
        ],
      },
      {
        __component: 'blocks.problem',
        eyebrow: 'What Growth Engine is not',
        heading: 'No random activity, cheap leads at any cost, or guaranteed-revenue theatre.',
        description: 'The work is designed to create evidence and qualified opportunity without pretending every variable is controllable.',
        items: [
          item('Not ads without tracking', 'Campaign delivery is connected to meaningful actions and a defined handoff.'),
          item('Not vanity reporting', 'Impressions and clicks are context, not the final definition of success.'),
          item('Not one funnel for every company', 'The mechanism adapts to the buying process, economics, and internal capacity.'),
          item('Not a revenue guarantee', 'Acquisition supports sales performance but cannot replace offer quality, response speed, fulfillment, or commercial judgment.'),
        ],
      },
      servicesEn(),
      {
        __component: 'legacy.faq',
        eyebrow: 'Before we start',
        heading: 'Growth Engine questions',
        items: [
          faq('Is Growth Engine only for paid advertising?', 'No. Paid campaigns are one possible channel. The same system can support organic attention, partnerships, outbound activity, or an existing audience.'),
          faq('Do we need a new website first?', 'Not always. A focused landing page may be enough to begin, while Website Engine is useful when the wider site is limiting trust, content, or conversion.'),
          faq('Will every capability be included?', 'No. Scope is selected after diagnosis. The goal is to build the smallest complete system that can produce useful evidence and qualified opportunities.'),
          faq('Do you guarantee leads or sales?', 'No. We build and improve the acquisition system, define useful measures, and make evidence-based decisions without guaranteeing outcomes outside our control.'),
        ],
      },
      {
        __component: 'blocks.final-cta',
        heading: 'Find the acquisition constraint before increasing the budget.',
        description: 'Start with a Growth Diagnosis focused on the offer, campaign path, qualification, measurement, and sales handoff.',
        primaryCta: cta('Request a Growth Diagnosis', '/book-call'),
        secondaryCta: cta('Explore Website Engine', '/website-development', 'secondary'),
      },
    ],
  },
  {
    slug: 'website-development',
    title: 'Website Engine',
    seo: {
      metaTitle: 'Website Engine | Conversion-Focused Website Development',
      metaDescription:
        'Build a conversion-focused business website with clear messaging, structured content, analytics, integrations, and a maintainable headless CMS.',
      keywords: 'business website development, conversion website, UI UX, headless CMS, website analytics',
      canonicalUrl: '/website-development',
      noIndex: false,
    },
    blocks: [
      {
        __component: 'blocks.page-hero',
        title: 'Build a website that works like a business system.',
        description:
          'Website Engine combines strategy, messaging, UX, development, structured content, integrations, and measurement so customers can understand, trust, and act—and your team can publish and grow.',
        primaryCta: cta('Request a Website Diagnosis', '/book-call'),
        secondaryCta: cta('See the build process', '#process', 'secondary'),
        imageKeyword: 'conversion-business-website',
      },
      {
        __component: 'blocks.problem',
        eyebrow: 'Beyond the online brochure',
        heading: 'A modern-looking website can still be a weak business asset.',
        description:
          'The website underperforms when it reflects internal departments instead of customer needs, hides the next step, or cannot evolve without fragile workarounds.',
        items: [
          item('Visitors cannot understand the company quickly', 'The value proposition, audience, services, and proof compete instead of guiding one clear journey.'),
          item('Every page uses the same generic CTA', 'Different levels of intent are forced into one action instead of forms, bookings, WhatsApp, demos, or resources suited to context.'),
          item('Content and tools are disconnected', 'Updates require developers while forms, analytics, CRM, calendars, and internal processes do not share useful context.'),
          item('The technology is the wrong size', 'The stack is either fragile and hard to maintain or more complex than the business actually needs.'),
        ],
      },
      {
        __component: 'blocks.dashboard-showcase',
        eyebrow: 'The website value system',
        heading: 'A valuable website reduces the distance between interest and action.',
        description: 'The experience should make the desired outcome easier to reach while lowering uncertainty and effort.',
        items: [
          metric('Understand', 'Less time', 'Customers grasp the company, offer, and relevance without decoding internal language.'),
          metric('Trust', 'More confidence', 'Message, proof, design, performance, and consistency support a credible decision.'),
          metric('Act', 'Less effort', 'Each important journey offers an appropriate, visible, and measurable next step.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'Strategy, structure, and message',
        heading: 'Architecture follows customer decisions and business goals.',
        description:
          'Before visual design, we clarify what the website must help the company and its customers accomplish.',
        items: [
          item('Business diagnosis', 'Objectives, audiences, current-site performance, technical constraints, conversion actions, content ownership, and growth needs.'),
          item('Customer journeys', 'The questions, proof, objections, and actions that matter for each important audience and level of intent.'),
          item('Information architecture', 'Sitemap, hierarchy, navigation, service and industry pages, resources, internal linking, search, or filtering where useful.'),
          item('Conversion messaging', 'Value proposition, page hierarchy, service copy, objection handling, trust elements, and contextual calls to action.'),
          item('Action design', 'Forms, booking, WhatsApp, quotation requests, demos, downloads, or another next step matched to the journey.'),
          item('Content responsibilities', 'A practical plan for what must be created, approved, maintained, and reused after launch.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'Design, build, and management',
        heading: 'A maintainable platform for customers and the team behind it.',
        description: 'Technical decisions are made in service of speed, clarity, publishing, measurement, and long-term maintainability.',
        items: [
          item('Responsive UI and UX', 'Accessible layouts, readable hierarchy, purposeful interactions, reusable components, and deliberate mobile behavior.'),
          item('Modern frontend architecture', 'A responsive React and Next.js frontend using the project’s established component and rendering patterns.'),
          item('Structured headless CMS', 'Strapi content models for reusable services, articles, products, case studies, people, FAQs, locations, and SEO data where needed.'),
          item('Secure conversion paths', 'Forms and API handling designed around validation, reliability, privacy, and clear confirmation states.'),
          item('Business integrations', 'Google Sheets, calendars, CRM, email, WhatsApp, payments, internal APIs, recruitment, analytics, or support tools when in scope.'),
          item('Launch and maintenance', 'Deployment, redirects, documentation, editor guidance, and a codebase the business is not afraid to change.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'Analytics, performance, and readiness',
        heading: 'Measurement should answer business questions—not merely count visitors.',
        description:
          'The foundation supports discoverability, stability, useful reporting, and optional future capabilities without sacrificing the human experience.',
        items: [
          item('Journey analytics', 'Traffic sources, important-page visits, form starts, completions, abandonment, bookings, WhatsApp clicks, downloads, search, and qualified inquiries.'),
          item('Performance foundations', 'Responsive loading, optimized media, stable layouts, efficient rendering, and sensible page weight.'),
          item('Technical SEO', 'Semantic structure, metadata, sitemaps, structured data, internal linking, indexing controls, redirects, and technical stability without ranking promises.'),
          item('Accessibility', 'Logical headings, keyboard support, visible focus, readable contrast, useful labels, and reduced-motion behavior.'),
          item('Structured publishing', 'Content can be updated once and reused across navigation, cards, pages, metadata, and related experiences.'),
          item('Optional AI readiness', 'Semantic content, explicit labels, predictable forms, machine-readable metadata, and controlled actions can support future assisted browsing.'),
          item('Progressive enhancement', 'Emerging approaches such as WebMCP may be evaluated where suitable, but core journeys never depend on experimental support.'),
        ],
      },
      {
        __component: 'blocks.process',
        eyebrow: 'How we build',
        heading: 'From diagnosis to a platform the business can improve.',
        description: 'The process keeps strategy, content, design, development, and validation connected.',
        steps: [
          step('Diagnose', 'Clarify objectives, audiences, current performance, constraints, content, and conversion priorities.'),
          step('Architect', 'Define journeys, sitemap, content models, integrations, and measurement requirements.'),
          step('Communicate', 'Build the message hierarchy, page narratives, objections, proof, and action strategy.'),
          step('Design', 'Create responsive UI, reusable patterns, and interaction behavior aligned with the brand.'),
          step('Build', 'Implement the frontend, CMS, forms, integrations, analytics, SEO, and deployment foundation.'),
          step('Validate', 'Test content, accessibility, performance, responsive behavior, integrations, and conversion paths.'),
          step('Launch', 'Publish with redirects, indexing controls, monitoring, and clear ownership in place.'),
          step('Improve', 'Use behavior and business outcomes to prioritize the next useful change.'),
        ],
      },
      {
        __component: 'blocks.problem',
        eyebrow: 'What Website Engine is not',
        heading: 'Not a decorative redesign, generic template, or abandoned stack.',
        description: 'The website earns its complexity by supporting a real customer or business need.',
        items: [
          item('Not disconnected pages', 'Navigation, content, calls to action, and analytics are designed as one system.'),
          item('Not animation for appearance', 'Motion is used only when it improves hierarchy, feedback, or understanding.'),
          item('Not an unmanageable CMS', 'Content structure is designed around how the team actually publishes and reuses information.'),
          item('Not experimental AI theatre', 'An optional AI-assisted layer never replaces a complete, reliable human interface.'),
          item('Not enterprise architecture by default', 'The simplest maintainable approach wins when extra complexity does not create value.'),
        ],
      },
      servicesEn(),
      {
        __component: 'legacy.faq',
        eyebrow: 'Before we start',
        heading: 'Website Engine questions',
        items: [
          faq('Can our team update the website?', 'Yes. Content responsibilities and structured CMS models are designed around the information your team needs to maintain, without forcing every edit through a developer.'),
          faq('Are integrations included?', 'Only the integrations required by the agreed customer journeys and internal workflow are included. Scope is confirmed after diagnosis.'),
          faq('Do you guarantee SEO rankings?', 'No. We implement strong technical and content foundations, but rankings depend on competition, authority, content, search behavior, and factors outside the website build.'),
          faq('Is the AI-ready layer required?', 'No. It is an optional readiness layer. The website remains fully useful and reliable without experimental standards or AI agents.'),
        ],
      },
      {
        __component: 'blocks.final-cta',
        heading: 'Plan the website around the decisions it needs to support.',
        description: 'Start with a Website Diagnosis covering customer journeys, content, conversion, technology, integrations, and measurement.',
        primaryCta: cta('Request a Website Diagnosis', '/book-call'),
        secondaryCta: cta('Explore Growth Engine', '/growth-system', 'secondary'),
      },
    ],
  },
  {
    slug: 'onboarding-engine',
    title: 'Onboarding Engine',
    seo: {
      metaTitle: 'Onboarding Engine | Client Onboarding Automation',
      metaDescription:
        'Design and automate client intake, documents, scheduling, project setup, and internal handoff from closed sale to delivery-ready project.',
      keywords: 'client onboarding, onboarding automation, client intake, workflow integration, AI assisted onboarding',
      canonicalUrl: '/onboarding-engine',
      noIndex: false,
    },
    blocks: [
      {
        __component: 'blocks.page-hero',
        title: 'Turn every closed customer into a delivery-ready project.',
        description:
          'Onboarding Engine designs and automates the journey from “new customer” to “ready for delivery,” reducing administrative work while giving customers and internal teams clear next steps.',
        primaryCta: cta('Audit Your Onboarding Process', '/book-call'),
        secondaryCta: cta('See the onboarding flow', '#process', 'secondary'),
        imageKeyword: 'client-onboarding-workflow',
      },
      {
        __component: 'blocks.problem',
        eyebrow: 'The post-sale gap',
        heading: 'The sale is closed. The customer still does not know what happens next.',
        description:
          'Businesses often invest heavily in acquisition and sales, then improvise the first operational experience through messages, memory, and manual reminders.',
        items: [
          item('Information is scattered', 'Answers, files, access details, payments, and decisions live across WhatsApp, email, forms, and individual employees.'),
          item('Project starts are delayed', 'Delivery begins without complete context or waits while the team repeatedly requests missing information and documents.'),
          item('Responsibilities are unclear', 'Customers and internal teams do not know who owns the next step, which requirements remain, or when kickoff can happen.'),
          item('The process depends on memory', 'Repetitive setup, reminders, task assignment, and internal notifications change depending on who handles the customer.'),
        ],
      },
      {
        __component: 'blocks.process',
        eyebrow: 'The onboarding mechanism',
        heading: 'A guided flow from sale confirmed to delivery ready.',
        description: 'The right workflow changes by service, package, customer, risk, and internal delivery model.',
        steps: [
          step('Welcome', 'Confirm the relationship, explain the journey, set expectations, and provide one clear starting point.', 'The customer knows what happens next.'),
          step('Intelligent intake', 'Collect package-specific business context, contacts, objectives, access, and requirements.', 'Questions adapt to what is actually needed.'),
          step('Documents', 'Request, organize, and validate agreements, assets, files, or confirmations.', 'Required information is visible and traceable.'),
          step('Validation', 'Detect gaps, trigger reminders, and keep human confirmation for sensitive steps.', 'Incomplete onboarding does not silently reach delivery.'),
          step('Internal brief', 'Summarize answers, decisions, risks, and responsibilities for the delivery team.', 'The team receives usable context.'),
          step('Project setup', 'Create records, folders, tasks, status, ownership, and notifications in the tools already used.', 'Repetitive setup happens consistently.'),
          step('Kickoff', 'Schedule the right meeting or handoff once readiness conditions are complete.', 'Everyone arrives prepared.'),
          step('Delivery ready', 'Confirm requirements, ownership, timing, and the first delivery milestone.', 'Work starts with fewer avoidable delays.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'What can be included',
        heading: 'One onboarding experience connected to the tools behind delivery.',
        description: 'Scope is selected around the current process, customer experience, risk, and operational return.',
        items: [
          item('Welcome and guidance', 'Personalized welcome messages, next steps, status, FAQs, and clear ownership.'),
          item('Dynamic client intake', 'Package-specific forms, conditional questions, validation, and progress-saving when appropriate.'),
          item('Documents and confirmation', 'File collection, agreement steps, payment confirmation, missing-item checks, and controlled approval.'),
          item('Scheduling and reminders', 'Calendar booking, deadlines, automated reminders, and escalation when human follow-up is required.'),
          item('Business-tool integration', 'CRM, Google Sheets, Drive, email, project tools, internal APIs, or another system already supporting delivery.'),
          item('Project creation', 'Folders, records, tasks, assignments, internal notifications, and customer-status tracking.'),
          item('Delivery handoff', 'A complete internal brief, readiness checks, kickoff preparation, and clear transfer to the responsible team.'),
          item('Client portal', 'A focused progress or resource page when visibility materially improves the experience.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'Practical AI assistance',
        heading: 'Use AI to reduce review work—not to remove responsible judgment.',
        description: 'AI is an optional capability for speed, clarity, classification, and communication within controlled workflows.',
        items: [
          item('Summarize intake', 'Turn long answers into a structured internal onboarding brief for review.'),
          item('Extract document information', 'Identify useful fields or requirements while preserving verification for sensitive data.'),
          item('Detect incomplete answers', 'Flag vague, contradictory, or missing information before the workflow progresses.'),
          item('Prepare next-step messages', 'Draft contextual reminders and guidance based on onboarding status.'),
          item('Route the workflow', 'Suggest the relevant package, team, checklist, or next step using explicit business rules and human oversight.'),
          item('Answer common questions', 'Provide controlled responses from approved onboarding information, with escalation when certainty is low.'),
        ],
      },
      {
        __component: 'blocks.dashboard-showcase',
        eyebrow: 'Operational visibility',
        heading: 'Measure how quickly and reliably customers become ready.',
        description: 'KPIs are selected around the process rather than presented as invented performance claims.',
        items: [
          metric('Completion', 'Readiness', 'Track completion rate, abandonment, and missing-document rate.'),
          metric('Time', 'Speed', 'Measure average completion time, customer response time, and payment-to-project-start time.'),
          metric('Follow-up', 'Effort', 'Count manual reminders, delayed onboardings, booking rate, and time to first value.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'Adapted to delivery',
        heading: 'Different businesses need different readiness conditions.',
        description: 'The workflow follows what must be true before the specific team can deliver well.',
        items: [
          item('Agencies', 'Collect brand assets, access credentials, objectives, stakeholders, approvals, and campaign history.'),
          item('Consultants', 'Gather business context, current challenges, documents, decision makers, and strategy-session inputs.'),
          item('Software companies', 'Create accounts, collect configuration requirements, validate access, and schedule implementation.'),
          item('Training businesses', 'Confirm enrollment, learner context, prerequisites, materials, cohort timing, and support routes.'),
          item('Real estate and services', 'Collect location, urgency, availability, documents, assignment information, and site-specific requirements.'),
          item('E-commerce', 'Support wholesale, supplier, partner, or high-touch customer onboarding with the right commercial and operational checks.'),
        ],
      },
      {
        __component: 'blocks.process',
        eyebrow: 'How we implement',
        heading: 'Simplify before automating.',
        description: 'The goal is a clearer process—not a complicated workflow created only to use more tools.',
        steps: [
          step('Audit', 'Review the current post-sale journey, delays, exceptions, tools, ownership, and customer communication.'),
          step('Map', 'Define the ideal flow, readiness conditions, decisions, roles, and handoff points.'),
          step('Simplify', 'Remove duplicate questions, unnecessary approvals, unclear language, and avoidable customer effort.'),
          step('Automate', 'Implement repeatable messages, reminders, validation, setup, and status changes.'),
          step('Integrate', 'Connect the smallest useful set of existing business tools and data destinations.'),
          step('Test', 'Run normal, incomplete, exception, and failure scenarios before release.'),
          step('Train', 'Document ownership, review points, overrides, and how the team handles exceptions.'),
          step('Optimize', 'Use completion, delay, follow-up, and readiness data to improve the process.'),
        ],
      },
      {
        __component: 'blocks.problem',
        eyebrow: 'What Onboarding Engine is not',
        heading: 'Automation should strengthen the relationship, not hide a broken process.',
        description: 'Sensitive decisions and important customer moments keep appropriate human control.',
        items: [
          item('Not a generic chatbot', 'Conversation is used only when it is the clearest interface for a real onboarding need.'),
          item('Not one workflow for every customer', 'Questions, requirements, and paths can change by package, risk, or customer type.'),
          item('Not disconnected automation tools', 'Each automated step belongs to one visible journey with clear ownership.'),
          item('Not removing people', 'Human confirmation and relationship-building remain where judgment, trust, or risk requires them.'),
        ],
      },
      servicesEn(),
      {
        __component: 'legacy.faq',
        eyebrow: 'Before we start',
        heading: 'Onboarding Engine questions',
        items: [
          faq('Do we need to replace our current tools?', 'Usually not. We first look for a simpler flow using the systems your team already understands, then add or replace tools only when there is a clear operational reason.'),
          faq('Can the workflow handle different packages?', 'Yes. Intake, requirements, reminders, approvals, and project setup can branch by service, package, customer type, or another explicit rule.'),
          faq('Does AI make onboarding decisions automatically?', 'Not for high-risk or sensitive steps. AI can assist with summaries, checks, drafts, and routing suggestions while humans retain confirmation and override control.'),
          faq('Can Onboarding Engine be purchased independently?', 'Yes. It can improve the post-sale journey even when acquisition and the main website are managed elsewhere.'),
        ],
      },
      {
        __component: 'blocks.final-cta',
        heading: 'Find where new customers get stuck before delivery begins.',
        description: 'Start with an onboarding audit covering information, documents, handoffs, tools, responsibilities, and readiness conditions.',
        primaryCta: cta('Audit Your Onboarding Process', '/book-call'),
        secondaryCta: cta('Explore Website Engine', '/website-development', 'secondary'),
      },
    ],
  },
];

const arabicPages = [
  {
    slug: 'home',
    title: 'الرئيسية',
    seo: {
      metaTitle: 'إنجاز ديجيتال | أنظمة النمو والمواقع وتأهيل العملاء',
      metaDescription: 'اربط اكتساب العملاء والموقع وتأهيل العملاء الجدد في أنظمة عملية من الانتباه إلى التسليم.',
      keywords: 'اكتساب العملاء, تطوير المواقع, تأهيل العملاء, أنظمة الأعمال',
      canonicalUrl: '/',
      noIndex: false,
    },
    blocks: [
      {
        __component: 'blocks.hero',
        title: 'ابن الأنظمة التي تنقل العميل من الانتباه إلى التسليم.',
        subtitle: 'تربط إنجاز ديجيتال بين اكتساب الطلب، التحويل، وتأهيل العملاء حتى يصبح النمو أوضح والتنفيذ أقل احتكاكا.',
        primaryCta: cta('احجز مكالمة استراتيجية', '/book-call'),
        secondaryCta: cta('استكشف المحركات الثلاثة', '#services', 'secondary'),
        align: 'left',
      },
      servicesAr(),
      {
        __component: 'blocks.process',
        eyebrow: 'رحلة العميل الكاملة',
        heading: 'كل مرحلة يجب أن تسهل المرحلة التي تليها.',
        description: 'الانتباه ← الاهتمام ← التحويل ← البيع ← التأهيل ← التسليم',
        steps: [
          step('الانتباه', 'الوصول إلى السوق المناسب بعرض ورسالة لهما صلة واضحة.'),
          step('الاهتمام', 'توضيح المشكلة والقيمة والخطوة التالية عبر المحتوى والإبداع.'),
          step('التحويل', 'تحويل الزيارات إلى نماذج أو حجوزات أو محادثات ذات معنى.'),
          step('البيع', 'تسليم الفرصة إلى الفريق بالسياق اللازم للمتابعة.'),
          step('التأهيل', 'جمع المعلومات والوثائق والتأكيدات والمواعيد في تدفق واحد.'),
          step('التسليم', 'تجهيز الملخص الداخلي والمشروع والمسؤوليات وشروط البداية.'),
        ],
      },
      {
        __component: 'blocks.final-cta',
        heading: 'حدد العائق قبل شراء خدمة منفصلة جديدة.',
        description: 'ابدأ بمكالمة تحدد هل الأولوية اليوم للنمو أم الموقع أم تأهيل العملاء.',
        primaryCta: cta('اطلب تشخيص النظام', '/book-call'),
        secondaryCta: cta('استكشف محرك النمو', '/growth-system', 'secondary'),
      },
    ],
  },
  {
    slug: 'growth-system',
    title: 'محرك النمو',
    seo: {
      metaTitle: 'محرك النمو | اكتساب العملاء وتوليد الطلب',
      metaDescription: 'ابن نظام اكتساب قابل للقياس يربط العرض والحملات وصفحات الهبوط والعملاء المؤهلين والتحسين.',
      keywords: 'اكتساب العملاء, توليد العملاء المحتملين, إعلانات مدفوعة, تحليلات التسويق',
      canonicalUrl: '/growth-system',
      noIndex: false,
    },
    blocks: [
      {
        __component: 'blocks.page-hero',
        title: 'حوّل استثمار التسويق إلى فرص أعمال مؤهلة.',
        description: 'يربط محرك النمو السوق والعرض والرسالة والإبداع والحملات وصفحة الهبوط والتأهيل والقياس داخل نظام اكتساب واحد.',
        primaryCta: cta('اطلب تشخيص النمو', '/book-call'),
        secondaryCta: cta('شاهد مسار الاكتساب', '#process', 'secondary'),
        imageKeyword: 'customer-acquisition-system',
      },
      {
        __component: 'blocks.problem',
        eyebrow: 'أين تضيع الميزانية',
        heading: 'شراء الإعلانات لا يعني بناء محرك اكتساب.',
        description: 'عندما ينفصل العرض والحملة والصفحة والتأهيل والمتابعة، تظهر أرقام كثيرة بدون قرار واضح.',
        items: [
          item('عرض غير مشخص', 'تزداد الميزانية قبل فهم قوة الوعد وملاءمته للسوق.'),
          item('الحملة والصفحة غير متطابقتين', 'يصل الزائر بتوقع ثم يجد رسالة مختلفة أو ثقة ضعيفة أو احتكاكا زائدا.'),
          item('التركيز على العميل الرخيص', 'ينخفض سعر العميل بينما تتجاهل الجودة والحجز والتواصل وفرصة البيع.'),
          item('العائق غير معروف', 'لا يعرف الفريق هل المشكلة في الجمهور أم الإبداع أم الرسالة أم الصفحة أم المتابعة.'),
        ],
      },
      {
        __component: 'blocks.process',
        eyebrow: 'آلية الاكتساب',
        heading: 'مسار مترابط من العرض إلى التحسين.',
        description: 'العرض ← الرسالة ← الإبداع ← الحملة ← صفحة الهبوط ← العميل المؤهل ← التحسين',
        steps: [
          step('العرض', 'توضيح السوق والمشكلة والنتيجة والبرهان.'),
          step('الرسالة', 'تحويل العرض إلى زوايا حملة ونص تحويل واضح.'),
          step('الإبداع', 'تطوير المفاهيم والنصوص وتوجيه التسجيل عند الحاجة.'),
          step('الحملة', 'بناء القناة والجمهور والميزانية وهيكل الاختبار.'),
          step('صفحة الهبوط', 'مطابقة الرسالة والثقة والاعتراضات والنموذج.'),
          step('عميل مؤهل', 'جمع السياق وتوجيهه إلى واتساب أو الحجز أو CRM أو Sheets.'),
          step('التحسين', 'قراءة الأداء عبر الرحلة وتحسين العائق الحقيقي.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'ما الذي يمكن تضمينه',
        heading: 'نظام يتكيف مع نموذج العمل لا مع قالب ثابت.',
        description: 'يتحدد النطاق حسب العرض ومسار البيع والقناة والقدرة الداخلية والبيانات المتاحة.',
        items: [
          item('تحليل السوق والعرض', 'بحث الجمهور والسياق التنافسي وهيكلة العرض والاستراتيجية.'),
          item('نظام الحملات', 'اختيار القنوات والاستهداف والهيكلة والإطلاق والاختبارات.'),
          item('النص والإبداع', 'نصوص الإعلان والمفاهيم وسيناريوهات الفيديو والتوجيه.'),
          item('صفحة الهبوط', 'الاستراتيجية والنص والتصميم والتطوير المتجاوب.'),
          item('تأهيل العملاء', 'نماذج وأسئلة تجمع ما يحتاجه فريق البيع.'),
          item('التكامل', 'واتساب والحجز وCRM وGoogle Sheets حسب الحاجة.'),
          item('القياس', 'أحداث التحويل ومؤشرات الأداء والتقارير.'),
          item('التحسين', 'تشخيص الأداء والتركيز على أضعف مرحلة.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'ذكاء مؤشرات الأداء',
        heading: 'قيمة المؤشر في علاقته بما قبله وما بعده.',
        description: 'نقرأ الوصول والنقر وسلوك الصفحة وجودة العميل والحجز وفرصة البيع، ونستخدم تكلفة الاكتساب والعائد عندما تتوفر بيانات مبيعات موثوقة.',
        items: [
          item('وصول مرتفع ونقر ضعيف', 'قد يشير إلى مشكلة في الجمهور أو العرض أو الرسالة أو الإبداع.'),
          item('نقر قوي وتحويل ضعيف', 'قد يشير إلى عدم تطابق الرسالة أو ضعف الثقة أو احتكاك الصفحة.'),
          item('تحويل جيد وجودة ضعيفة', 'قد يشير إلى تأهيل ضعيف أو استهداف واسع أو وعد يجذب نية خاطئة.'),
          item('عملاء جيدون ومبيعات ضعيفة', 'قد يكشف بطء الرد أو المتابعة أو عائقا في عملية البيع.'),
        ],
      },
      {
        __component: 'blocks.process',
        eyebrow: 'منهجية العمل',
        heading: 'نشخص، نصمم، نبني، نطلق، نتعلم، ثم نحسن.',
        steps: [
          step('نشخص', 'نراجع السوق والعرض والرحلة والبيانات والتسليم إلى المبيعات.'),
          step('نصمم', 'نحدد الاستراتيجية والقياس والاختبارات والأصول.'),
          step('نبني', 'ننشىء مكونات الحملة والصفحة والتأهيل والتتبع.'),
          step('نطلق', 'نختبر المسار كاملا ونحدد خط الأساس.'),
          step('نتعلم', 'نجمع إشارة كافية لتمييز الضوضاء عن العائق.'),
          step('نحسن', 'نحسن المرحلة الأعلى أثرا على الفرص المؤهلة.'),
        ],
      },
      servicesAr(),
      {
        __component: 'blocks.final-cta',
        heading: 'حدد عائق الاكتساب قبل زيادة الميزانية.',
        description: 'ابدأ بتشخيص العرض والحملة والتأهيل والقياس والتسليم إلى المبيعات.',
        primaryCta: cta('اطلب تشخيص النمو', '/book-call'),
        secondaryCta: cta('استكشف محرك الموقع', '/website-development', 'secondary'),
      },
    ],
  },
  {
    slug: 'website-development',
    title: 'محرك الموقع',
    seo: {
      metaTitle: 'محرك الموقع | تطوير مواقع أعمال موجهة للتحويل',
      metaDescription: 'ابن موقع أعمال برسائل واضحة ومحتوى منظم وقياس وتكاملات ونظام إدارة قابل للصيانة.',
      keywords: 'تطوير مواقع الأعمال, موقع موجه للتحويل, تجربة المستخدم, Strapi, تحليلات الموقع',
      canonicalUrl: '/website-development',
      noIndex: false,
    },
    blocks: [
      {
        __component: 'blocks.page-hero',
        title: 'ابن موقعا يعمل كنظام أعمال.',
        description: 'يجمع محرك الموقع بين الاستراتيجية والرسائل وتجربة المستخدم والتطوير والمحتوى المنظم والتكامل والقياس حتى يفهم العميل ويثق ويتخذ الإجراء.',
        primaryCta: cta('اطلب تشخيص الموقع', '/book-call'),
        secondaryCta: cta('شاهد عملية البناء', '#process', 'secondary'),
        imageKeyword: 'conversion-business-website',
      },
      {
        __component: 'blocks.problem',
        eyebrow: 'أبعد من الكتيب الرقمي',
        heading: 'قد يبدو الموقع حديثا ويبقى أصلا ضعيفا.',
        description: 'يضعف الموقع عندما يعكس أقسام الشركة بدل احتياجات العميل أو يخفي الخطوة التالية أو يصعب تحديثه.',
        items: [
          item('الفهم بطيء', 'تتنافس الرسالة والخدمات والبرهان بدلا من توجيه رحلة واضحة.'),
          item('دعوة عامة في كل صفحة', 'تجبر مستويات النية المختلفة على إجراء واحد غير مناسب.'),
          item('المحتوى والأدوات منفصلة', 'تحتاج التحديثات إلى مطور بينما النماذج والتحليلات والأنظمة لا تشارك سياقا مفيدا.'),
          item('تقنية بالحجم الخطأ', 'البنية إما هشة وصعبة الصيانة أو أعقد مما يحتاجه العمل.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'الاستراتيجية والبنية والرسالة',
        heading: 'تتبع البنية قرارات العميل وأهداف العمل.',
        items: [
          item('تشخيص العمل', 'الأهداف والجمهور والأداء والقيود والإجراءات والمحتوى والنمو المستقبلي.'),
          item('رحلات العميل', 'الأسئلة والبرهان والاعتراضات والإجراءات المهمة لكل جمهور.'),
          item('هندسة المعلومات', 'خريطة الصفحات والتنقل والخدمات والقطاعات والموارد والربط والبحث.'),
          item('رسائل التحويل', 'القيمة وتسلسل الصفحة ونص الخدمات والاعتراضات والثقة.'),
          item('تصميم الإجراء', 'النماذج والحجز وواتساب وطلب السعر والعروض والموارد.'),
          item('مسؤولية المحتوى', 'خطة عملية للإنشاء والموافقة والصيانة وإعادة الاستخدام.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'التصميم والبناء والإدارة',
        heading: 'منصة قابلة للصيانة للعميل والفريق.',
        items: [
          item('واجهة وتجربة متجاوبة', 'وصول وقراءة وتسلسل وتفاعل وسلوك جوال مقصود.'),
          item('واجهة حديثة', 'React وNext.js ومكونات قابلة لإعادة الاستخدام ضمن البنية القائمة.'),
          item('نظام محتوى منظم', 'Strapi لنمذجة الخدمات والمقالات والمنتجات والحالات والأسئلة وSEO.'),
          item('مسارات تحويل آمنة', 'نماذج وواجهات API مع التحقق والموثوقية والخصوصية والتأكيد.'),
          item('تكاملات الأعمال', 'Sheets والتقويم وCRM والبريد وواتساب والدفع والواجهات الداخلية عند الحاجة.'),
          item('الإطلاق والصيانة', 'النشر والتحويلات والوثائق وإرشاد المحررين وقاعدة كود قابلة للتغيير.'),
        ],
      },
      {
        __component: 'blocks.process',
        eyebrow: 'كيف نبني',
        heading: 'من التشخيص إلى منصة يمكن تحسينها.',
        steps: [
          step('نشخص', 'نوضح الأهداف والجمهور والأداء والقيود والمحتوى.'),
          step('نؤسس البنية', 'نحدد الرحلات وخريطة الصفحات والمحتوى والتكامل والقياس.'),
          step('نصوغ الرسالة', 'نبني تسلسل الصفحات والاعتراضات والبرهان والإجراء.'),
          step('نصمم', 'نصمم واجهة متجاوبة وأنماطا قابلة لإعادة الاستخدام.'),
          step('نبني', 'ننفيذ الواجهة وCMS والنماذج والتكامل والتحليلات وSEO.'),
          step('نتحقق', 'نختبر المحتوى والوصول والأداء والاستجابة والتكامل.'),
          step('نطلق', 'ننشر مع التحويلات والفهرسة والملكية الواضحة.'),
          step('نحسن', 'نستخدم السلوك والنتائج لاختيار التغيير التالي.'),
        ],
      },
      servicesAr(),
      {
        __component: 'blocks.final-cta',
        heading: 'خطط الموقع حول القرارات التي يجب أن يدعمها.',
        description: 'ابدأ بتشخيص الرحلات والمحتوى والتحويل والتقنية والتكامل والقياس.',
        primaryCta: cta('اطلب تشخيص الموقع', '/book-call'),
        secondaryCta: cta('استكشف محرك النمو', '/growth-system', 'secondary'),
      },
    ],
  },
  {
    slug: 'onboarding-engine',
    title: 'محرك التأهيل',
    seo: {
      metaTitle: 'محرك التأهيل | أتمتة تأهيل العملاء',
      metaDescription: 'صمم وأتمت جمع المعلومات والوثائق والمواعيد وتجهيز المشروع والتسليم الداخلي من البيع إلى الجاهزية.',
      keywords: 'تأهيل العملاء, أتمتة التأهيل, جمع بيانات العميل, تكامل سير العمل',
      canonicalUrl: '/onboarding-engine',
      noIndex: false,
    },
    blocks: [
      {
        __component: 'blocks.page-hero',
        title: 'حوّل كل عميل جديد إلى مشروع جاهز للتنفيذ.',
        description: 'يصمم محرك التأهيل الرحلة من العميل الجديد إلى الجاهزية، ليقل العمل الإداري وتصبح الخطوات أوضح للعميل والفريق.',
        primaryCta: cta('راجع عملية التأهيل', '/book-call'),
        secondaryCta: cta('شاهد تدفق التأهيل', '#process', 'secondary'),
        imageKeyword: 'client-onboarding-workflow',
      },
      {
        __component: 'blocks.problem',
        eyebrow: 'الفجوة بعد البيع',
        heading: 'تم البيع، لكن العميل لا يعرف ماذا يحدث بعد ذلك.',
        description: 'تستثمر الشركات في التسويق والبيع ثم تدير أول تجربة تشغيلية عبر الرسائل والذاكرة والتذكير اليدوي.',
        items: [
          item('معلومات مشتتة', 'الإجابات والملفات والتأكيدات موزعة بين واتساب والبريد والنماذج والأفراد.'),
          item('بداية متأخرة', 'ينتظر التنفيذ معلومات ناقصة أو يبدأ بدون سياق كاف.'),
          item('مسؤوليات غير واضحة', 'لا يعرف العميل أو الفريق من يملك الخطوة التالية أو ما الذي ينقص.'),
          item('اعتماد على الذاكرة', 'يتغير الإعداد والتذكير والتكليف حسب الشخص المسؤول.'),
        ],
      },
      {
        __component: 'blocks.process',
        eyebrow: 'آلية التأهيل',
        heading: 'تدفق موجه من تأكيد البيع إلى الجاهزية.',
        description: 'تأكيد البيع ← الترحيب ← جمع المعلومات ← الوثائق ← التحقق ← الملخص الداخلي ← إنشاء المشروع ← الانطلاق',
        steps: [
          step('الترحيب', 'شرح الرحلة والتوقعات ونقطة البداية.'),
          step('جمع ذكي', 'أسئلة حسب الباقة والسياق والأهداف والمتطلبات.'),
          step('الوثائق', 'طلب وتنظيم والتحقق من الملفات والتأكيدات.'),
          step('التحقق', 'كشف النواقص والتذكير مع إبقاء تأكيد الإنسان للخطوات الحساسة.'),
          step('ملخص داخلي', 'تلخيص الإجابات والقرارات والمخاطر والمسؤوليات.'),
          step('إنشاء المشروع', 'إنشاء السجلات والمجلدات والمهام والملكية والإشعارات.'),
          step('الانطلاق', 'جدولة الاجتماع أو التسليم عند اكتمال شروط الجاهزية.'),
          step('جاهز للتنفيذ', 'تأكيد المتطلبات والمسؤوليات والتوقيت وأول معلم.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'ما الذي يمكن تضمينه',
        heading: 'تجربة واحدة متصلة بأدوات التنفيذ.',
        items: [
          item('الترحيب والإرشاد', 'رسائل وخطوات وحالة وأسئلة شائعة وملكية واضحة.'),
          item('جمع ديناميكي', 'نماذج حسب الباقة وأسئلة شرطية وتحقق وحفظ التقدم.'),
          item('الوثائق والتأكيد', 'جمع الملفات والعقود والدفع والتحقق من النواقص.'),
          item('المواعيد والتذكير', 'الحجز والمواعيد والتذكيرات والتصعيد للمتابعة البشرية.'),
          item('التكامل', 'CRM وSheets وDrive والبريد وأدوات المشاريع والواجهات الداخلية.'),
          item('إنشاء المشروع', 'المجلدات والسجلات والمهام والتكليف والإشعارات والحالة.'),
          item('التسليم للتنفيذ', 'ملخص كامل وفحص الجاهزية وتحضير اجتماع البداية.'),
          item('بوابة العميل', 'صفحة تقدم أو موارد عندما تحسن الرؤية التجربة فعلا.'),
        ],
      },
      {
        __component: 'blocks.feature-list',
        eyebrow: 'مساعدة عملية بالذكاء الاصطناعي',
        heading: 'تقليل عمل المراجعة بدون إزالة الحكم المسؤول.',
        items: [
          item('تلخيص الإجابات', 'تحويل الإجابات الطويلة إلى ملخص داخلي منظم للمراجعة.'),
          item('استخراج المعلومات', 'تحديد الحقول المفيدة من الوثائق مع التحقق للبيانات الحساسة.'),
          item('كشف النواقص', 'تمييز الإجابات الغامضة أو المتعارضة أو الناقصة.'),
          item('إعداد الرسائل', 'صياغة تذكيرات وخطوات تالية حسب حالة التأهيل.'),
          item('توجيه المسار', 'اقتراح الباقة أو الفريق أو القائمة المناسبة بقواعد واضحة وإشراف بشري.'),
          item('الإجابة عن الأسئلة', 'ردود من معلومات معتمدة مع التصعيد عند انخفاض الثقة.'),
        ],
      },
      {
        __component: 'blocks.process',
        eyebrow: 'كيف ننفذ',
        heading: 'نبسط قبل أن نؤتمت.',
        steps: [
          step('نراجع', 'نراجع الرحلة والتأخير والاستثناءات والأدوات والملكية.'),
          step('نرسم', 'نحدد التدفق وشروط الجاهزية والقرارات والتسليم.'),
          step('نبسط', 'نزيل التكرار والموافقات غير الضرورية واللغة الغامضة.'),
          step('نؤتمت', 'ننفيذ الرسائل والتذكير والتحقق والإعداد والحالة.'),
          step('نربط', 'نصل أقل عدد مفيد من الأدوات والبيانات.'),
          step('نختبر', 'نختبر الحالات الطبيعية والناقصة والاستثنائية والفشل.'),
          step('ندرب', 'نوثق الملكية والمراجعة والتجاوز والاستثناءات.'),
          step('نحسن', 'نستخدم بيانات الاكتمال والتأخير والجاهزية للتحسين.'),
        ],
      },
      servicesAr(),
      {
        __component: 'blocks.final-cta',
        heading: 'حدد أين يتعطل العميل قبل بداية التنفيذ.',
        description: 'ابدأ بمراجعة المعلومات والوثائق والتسليم والأدوات والمسؤوليات وشروط الجاهزية.',
        primaryCta: cta('راجع عملية التأهيل', '/book-call'),
        secondaryCta: cta('استكشف محرك الموقع', '/website-development', 'secondary'),
      },
    ],
  },
];

const homepageEn = {
  slug: 'home',
  title: 'Home',
  seo: {
    metaTitle: 'Injaaz Digital | Digital Systems for Meaningful Progress',
    metaDescription: 'Injaaz Digital designs connected growth and website systems that turn objectives, technology, data, and execution into clearer, measurable progress.',
    keywords: 'digital systems, meaningful progress, customer acquisition, website systems',
    canonicalUrl: '/',
    noIndex: false,
  },
  blocks: [
    {
      __component: 'blocks.hero',
      eyebrow: 'Digital systems for meaningful progress',
      title: 'We design the systems through which intention becomes achievement.',
      subtitle: 'Injaaz Digital brings strategy, technology, design, data, and execution into one coherent structure—so that scattered activity becomes clear, measurable progress.',
      primaryCta: cta('Begin with the system', '/book-call'),
      secondaryCta: cta('Explore our work', '#services', 'secondary'),
      align: 'left',
    },
    {
      __component: 'blocks.animated-text',
      eyebrow: 'The meaning of Injaaz',
      text: 'Injaaz is not activity. It is not movement without direction. It is the moment intention takes form and effort becomes progress. Digital is the structure through which that progress can be designed, measured, repeated, and improved.',
      highlightedText: 'effort becomes progress',
      alignment: 'left',
      size: 'medium',
      animationStyle: 'progressive-opacity',
      sticky: true,
      theme: 'contrast',
    },
    {
      __component: 'blocks.problem',
      eyebrow: 'The central tension',
      heading: 'More activity does not always create more progress.',
      description: 'Before adding more, the flow must be understood.',
      items: [
        item('More advertising', 'Does not repair a weak offer.'),
        item('More traffic', 'Does not repair unclear positioning.'),
        item('More tools', 'Do not repair a broken process.'),
        item('More data', 'Does not create better decisions by itself.'),
        item('More technology', 'Can create more complexity when no clear system exists.'),
      ],
    },
    {
      __component: 'blocks.system-flow',
      eyebrow: 'Every company is a system',
      heading: 'Every company is a system.',
      description: 'A company is not a collection of isolated departments, campaigns, pages, and tools. It is a living system of people, decisions, processes, technology, and feedback.',
      steps: ['Inputs', 'Decisions', 'Actions', 'Results', 'Feedback', 'Improvement'].map((title) => item(title, '')),
      signals: ['Market', 'Offer', 'Communication', 'Customer experience', 'Technology', 'Operations', 'Measurement', 'Decisions'].map((title) => item(title, '')),
      closingStatement: 'When one part changes, the whole system responds.',
      variant: 'system',
    },
    servicesEn(),
    {
      __component: 'blocks.diagnosis',
      eyebrow: 'From symptom to system',
      heading: 'The visible problem may not be where the real problem began.',
      items: [
        { visibleProblem: 'Advertising is becoming expensive.', deeperSystem: 'The offer may be weak, the message unclear, the page disconnected, or the sales response too slow.' },
        { visibleProblem: 'The website does not convert.', deeperSystem: 'The positioning may be unclear, trust may be missing, or the customer journey may have no natural next step.' },
        { visibleProblem: 'The leads are poor quality.', deeperSystem: 'The targeting, promise, qualification, or follow-up process may be attracting the wrong attention.' },
      ],
      closingStatement: 'A symptom asks for a quick fix. A system asks for understanding.',
    },
    {
      __component: 'blocks.process',
      eyebrow: 'The Injaaz method',
      heading: 'We do not begin with the deliverable. We begin with the movement it must create.',
      description: 'A coherent method for turning a complex objective into an operable, measurable system.',
      variant: 'editorial',
      steps: [
        step('Understand', 'Study the objective, context, audience, constraints, and current state.'),
        step('Map', 'Make the complete flow visible, including people, tools, decisions, dependencies, and handoffs.'),
        step('Diagnose', 'Separate symptoms from causes and identify where progress is being lost.'),
        step('Design', 'Create a system in which strategy, message, experience, technology, and measurement reinforce one another.'),
        step('Build', 'Turn the design into a functional, maintainable, and usable digital system.'),
        step('Measure', 'Observe the signals that influence decisions, not only the numbers that look impressive.'),
        step('Improve', 'Use real feedback to refine the system over time.'),
      ],
    },
    {
      __component: 'blocks.system-flow',
      eyebrow: 'Measurement and feedback',
      heading: 'A system becomes intelligent when it can observe its own results.',
      description: 'A number alone says very little. Its meaning appears when it is connected to the stage before it, the stage after it, and the decision it should influence.',
      steps: ['Attention', 'Engagement', 'Conversion', 'Qualification', 'Contact', 'Opportunity', 'Customer'].map((title) => item(title, '')),
      signals: [
        item('Strong traffic, weak conversion', 'Examine message match, value, trust, and landing-page friction.'),
        item('Strong conversion, weak lead quality', 'Examine targeting, promise, qualification, and intent.'),
        item('Strong lead quality, weak contact', 'Examine routing, response time, ownership, and sales follow-up.'),
        item('Strong design, no measurable action', 'Clarify the next step and the event that should inform a decision.'),
        item('Good clicks, message mismatch', 'Reconnect campaign expectation with the landing-page experience.'),
      ],
      closingStatement: 'Useful KPIs connect impressions, reach, frequency, click-through rate, cost per click, landing-page views, conversion, lead quality, booking, contact, opportunity, and acquisition cost when reliable sales data exists.',
      variant: 'measurement',
    },
    {
      __component: 'blocks.principles',
      eyebrow: 'Why Injaaz Digital',
      heading: 'The work is designed as a system, not a collection of claims.',
      items: [
        item('Systems before symptoms', 'We search for the structure behind the visible problem.'),
        item('Strategy connected to execution', 'The thinking becomes design, software, campaigns, integrations, and measurable action.'),
        item('Technology with purpose', 'A tool is valuable only when it clarifies the process, strengthens the decision, or improves the result.'),
        item('Measurement connected to judgment', 'Data should support understanding, not replace it.'),
        item('Built to operate', 'The work should remain useful after the day it is launched.'),
        item('Improvement through feedback', 'Every result becomes an input for the next decision.'),
      ],
    },
    {
      __component: 'blocks.faq',
      eyebrow: 'Common questions',
      heading: 'A clearer starting point.',
      description: 'The first conversation is designed to identify the real constraint before choosing what to build.',
      items: [
        faq('What does Injaaz Digital build?', 'We build connected website and growth systems that clarify the offer, guide customers toward action, and make improvement measurable.'),
        faq('Do I need to know which service I need?', 'No. We begin with the objective and the point where progress is being lost, then recommend the most useful starting system.'),
        faq('Is this only design or development?', 'No. Design and development are part of the work, but they are connected to positioning, customer journeys, operations, measurement, and business outcomes.'),
        faq('Can you improve an existing website or process?', 'Yes. We first diagnose what is already working, what is disconnected, and whether improvement or a focused rebuild is the better decision.'),
        faq('What happens after the strategy call?', 'You receive a clear recommendation for the next step, expected scope, and the system that should be addressed first.'),
      ],
    },
    {
      __component: 'blocks.problem',
      eyebrow: 'Who this work is for',
      heading: 'For companies ready to replace scattered effort with deliberate progress.',
      description: 'The work is relevant to small and growing companies, service businesses, consultants, agencies, and local companies when the situation demands a clearer system.',
      items: [
        item('Attention without a clear conversion path', 'The company is visible, but interest has no coherent route to action.'),
        item('Value that is difficult to communicate', 'A serious service business needs its message and experience to carry the real value.'),
        item('Disconnected tools and processes', 'Growth has exposed handoff gaps, duplicated work, or missing ownership.'),
        item('Marketing without a complete acquisition view', 'Investment is increasing without clarity across offer, campaign, page, lead, and response.'),
        item('A website behind the company’s ambition', 'The digital presence no longer supports trust, action, or future growth.'),
        item('Measurement before the next decision', 'The team needs useful signals, not another collection of numbers.'),
      ],
    },
    {
      __component: 'legacy.editorial-content',
      eyebrow: 'The larger direction',
      heading: 'The work begins with growth and websites, but the direction is larger.',
      body: 'Growth and websites are where the work begins. The larger direction is the design of clearer systems across customer experience, operations, automation, and decision-making.',
      closingStatement: 'Not more technology for its own sake. Better structures through which people and technology can produce meaningful progress together.',
      variant: 'vision',
    },
    {
      __component: 'blocks.final-cta',
      heading: 'Begin with the place where progress is being lost.',
      description: 'The first step is not choosing a service. It is understanding the system, the objective, and the distance between them.',
      primaryCta: cta('Start a conversation', '/book-call'),
    },
  ],
};

const aboutEn = {
  slug: 'about',
  title: 'About Injaaz Digital',
  seo: {
    metaTitle: 'About Injaaz Digital | From Intention to Achievement',
    metaDescription: 'Discover the meaning, philosophy, mission, vision, and systems-thinking foundation behind Injaaz Digital.',
    keywords: 'Injaaz Digital, systems thinking, mission, vision, achievement',
    canonicalUrl: '/about',
    noIndex: false,
  },
  blocks: [
    {
      __component: 'blocks.page-hero',
      eyebrow: 'About Injaaz Digital',
      title: 'We believe achievement begins when effort finds direction.',
      description: 'Injaaz Digital is a digital systems company built around a simple idea: meaningful progress does not come from isolated activity. It appears when intention, people, processes, technology, and feedback move together.',
      imageKeyword: 'digital-systems-company',
      variant: 'visual',
    },
    {
      __component: 'legacy.editorial-content',
      eyebrow: 'Why Injaaz',
      heading: 'Injaaz is the movement from intention into reality.',
      body: 'Injaaz is an Arabic word that carries the meaning of achievement—of bringing something from intention into reality.\n\nIt is not merely movement or activity. It is effort that has found its form, its direction, and its result.\n\nDigital is the medium through which this philosophy takes shape: software, design, data, automation, communication, and the systems that connect them.\n\nModern companies rarely suffer from a lack of tools. They suffer from a lack of coherence. A website may be disconnected from the company’s value. Advertising may be disconnected from the sales process. Data may exist without influencing decisions. Tools may create more work instead of reducing it.',
      closingStatement: 'Injaaz Digital exists to bring these separate parts into a clearer whole.',
      variant: 'default',
    },
    {
      __component: 'blocks.timeline',
      eyebrow: 'Origin',
      heading: 'Our Starting Line',
      stages: [
        step('A way of seeing', 'Injaaz began with a way of looking at problems: not as isolated failures, but as parts of a larger system.'),
        step('An engineering foundation', 'Software engineering taught us to follow flows, examine dependencies, identify causes, handle complexity, and improve through feedback.'),
        step('A realization', 'More software, more advertising, and more data do not necessarily create better results. They become valuable only when they belong to a clear objective and a coherent process.'),
        step('The present direction', 'Injaaz Digital emerged from the desire to connect business thinking with technology, design, data, and execution—giving ambition a structure through which it can become achievement.'),
      ],
    },
    {
      __component: 'legacy.editorial-content',
      eyebrow: 'How we think',
      heading: 'The visible problem is rarely the whole problem.',
      body: 'We approach business problems as engineers approach complex systems: by understanding the whole, breaking it into meaningful parts, tracing the movement between them, and finding where the intended result is being lost.\n\nA company contains people, incentives, decisions, communication, customers, time, money, processes, technology, and feedback. A website can shape trust. A message can shape demand. A process can shape response time. A metric can shape a decision. A decision can shape the next result.',
      statements: [
        item('Effort without direction becomes exhaustion.', ''),
        item('Technology without purpose becomes complexity.', ''),
        item('Data without judgment becomes noise.', ''),
        item('Strategy without execution remains an intention.', ''),
        item('Execution without feedback repeats itself.', ''),
      ],
      closingStatement: 'Progress begins when these elements move as one.',
      variant: 'manifesto',
    },
    {
      __component: 'blocks.statement-pair',
      eyebrow: 'Mission and vision',
      first: {
        label: 'Our mission',
        statement: 'To turn intention into structure, effort into progress, and digital capability into meaningful achievement.',
        explanation: 'We bring strategy, technology, design, data, and execution into systems that are clear enough to operate and intelligent enough to improve.',
      },
      second: {
        label: 'Our vision',
        statement: 'We envision a world where progress is not left to chance.',
        explanation: 'Where technology does not create more noise, tools do not create more complexity, and effort is not lost in disconnected actions.\n\nWhere every objective has a path, every action belongs to a larger system, and every result becomes the beginning of a wiser decision.',
      },
    },
    {
      __component: 'blocks.principles',
      eyebrow: 'Principles and direction',
      heading: 'The standards that keep the work deliberate.',
      items: [
        item('Understand before building', 'Clarity must come before execution.'),
        item('Fix the system, not only the symptom', 'Visible problems often begin elsewhere.'),
        item('Use technology with purpose', 'Technology must improve the work, not merely decorate it.'),
        item('Measure what guides decisions', 'Not every available number deserves attention.'),
        item('Improve through feedback', 'Every result should inform what comes next.'),
      ],
      directionHeading: 'Where we are going',
      directionBody: 'Injaaz Digital begins with the systems through which companies meet the market: their digital presence and their path to customer acquisition.\n\nThe larger direction extends further—toward clearer customer experiences, stronger operations, purposeful automation, and better structures for decision-making.',
      closingStatement: 'The destination is not more digital activity. It is a more deliberate form of progress.',
    },
    {
      __component: 'blocks.final-cta',
      heading: 'Every achievement begins as an intention. What gives it reality is the system built between them.',
      primaryCta: cta('Start a conversation', '/book-call'),
    },
  ],
};

const homepageAr = {
  ...homepageEn,
  title: 'الرئيسية',
  seo: {
    metaTitle: 'إنجاز ديجيتال | أنظمة رقمية لتقدم ذي معنى',
    metaDescription: 'تصمم إنجاز ديجيتال أنظمة نمو ومواقع مترابطة تحول الأهداف والتقنية والبيانات والتنفيذ إلى تقدم أوضح وقابل للقياس.',
    keywords: 'أنظمة رقمية, تقدم, اكتساب العملاء, أنظمة المواقع',
    canonicalUrl: '/',
    noIndex: false,
  },
  blocks: [
    { __component: 'blocks.hero', eyebrow: 'أنظمة رقمية لتقدم ذي معنى', title: 'نصمم الأنظمة التي تتحول عبرها النية إلى إنجاز.', subtitle: 'تجمع إنجاز ديجيتال الاستراتيجية والتقنية والتصميم والبيانات والتنفيذ في بنية واحدة، ليتحول النشاط المتفرق إلى تقدم واضح وقابل للقياس.', primaryCta: cta('ابدأ من النظام', '/book-call'), secondaryCta: cta('استكشف عملنا', '#services', 'secondary'), align: 'left' },
    { __component: 'blocks.animated-text', eyebrow: 'معنى إنجاز', text: 'إنجاز ليس مجرد نشاط. وليس حركة بلا اتجاه. إنه اللحظة التي تتخذ فيها النية شكلا ويتحول الجهد إلى تقدم. والرقمي هو البنية التي تسمح بتصميم هذا التقدم وقياسه وتكراره وتحسينه.', highlightedText: 'يتحول الجهد إلى تقدم', alignment: 'left', size: 'medium', animationStyle: 'progressive-opacity', sticky: true, theme: 'contrast' },
    { __component: 'blocks.problem', eyebrow: 'التوتر المركزي', heading: 'المزيد من النشاط لا يصنع دائما المزيد من التقدم.', description: 'قبل أن نضيف المزيد، يجب أن نفهم التدفق.', items: [item('مزيد من الإعلان', 'لا يصلح عرضا ضعيفا.'), item('مزيد من الزيارات', 'لا يصلح تموضعا غير واضح.'), item('مزيد من الأدوات', 'لا يصلح عملية مكسورة.'), item('مزيد من البيانات', 'لا يصنع قرارا أفضل وحده.'), item('مزيد من التقنية', 'قد يزيد التعقيد عند غياب نظام واضح.')] },
    { __component: 'blocks.system-flow', eyebrow: 'كل شركة هي نظام', heading: 'كل شركة هي نظام.', description: 'الشركة ليست أقساما وحملات وصفحات وأدوات منفصلة، بل نظام حي من الناس والقرارات والعمليات والتقنية والتغذية الراجعة.', steps: ['المدخلات', 'القرارات', 'الأفعال', 'النتائج', 'التغذية الراجعة', 'التحسين'].map((title) => item(title, '')), signals: ['السوق', 'العرض', 'التواصل', 'تجربة العميل', 'التقنية', 'العمليات', 'القياس', 'القرارات'].map((title) => item(title, '')), closingStatement: 'عندما يتغير جزء، يستجيب النظام كله.', variant: 'system' },
    servicesAr(),
    { __component: 'blocks.diagnosis', eyebrow: 'من العرض إلى النظام', heading: 'قد لا تبدأ المشكلة الحقيقية من مكان ظهورها.', items: [{ visibleProblem: 'أصبح الإعلان مكلفا.', deeperSystem: 'قد يكون العرض ضعيفا أو الرسالة غير واضحة أو الصفحة منفصلة أو الاستجابة بطيئة.' }, { visibleProblem: 'الموقع لا يحول.', deeperSystem: 'قد يكون التموقع غامضا أو الثقة ناقصة أو الرحلة بلا خطوة تالية طبيعية.' }, { visibleProblem: 'جودة العملاء المحتملين ضعيفة.', deeperSystem: 'قد يجذب الاستهداف أو الوعد أو التأهيل أو المتابعة الانتباه الخطأ.' }], closingStatement: 'العرض يطلب إصلاحا سريعا. النظام يطلب فهما.' },
    { __component: 'blocks.process', eyebrow: 'منهج إنجاز', heading: 'لا نبدأ بالمخرج. نبدأ بالحركة التي يجب أن يصنعها.', description: 'منهج مترابط يحول الهدف المعقد إلى نظام قابل للتشغيل والقياس.', variant: 'editorial', steps: [step('نفهم', 'ندرس الهدف والسياق والجمهور والقيود والحالة الحالية.'), step('نرسم', 'نجعل التدفق الكامل مرئيا بما فيه الأشخاص والأدوات والقرارات والتسليم.'), step('نشخص', 'نفصل الأعراض عن الأسباب ونحدد موضع فقدان التقدم.'), step('نصمم', 'نربط الاستراتيجية والرسالة والتجربة والتقنية والقياس.'), step('نبني', 'نحول التصميم إلى نظام عملي وقابل للصيانة.'), step('نقيس', 'نراقب الإشارات التي تؤثر في القرار.'), step('نحسن', 'نستخدم التغذية الراجعة لتحسين النظام.')] },
    { __component: 'blocks.system-flow', eyebrow: 'القياس والتغذية الراجعة', heading: 'يصبح النظام ذكيا عندما يستطيع ملاحظة نتائجه.', description: 'لا يقول الرقم الكثير وحده؛ يظهر معناه عندما يرتبط بالمرحلة قبله وبعده وبالقرار الذي يجب أن يؤثر فيه.', steps: ['الانتباه', 'التفاعل', 'التحويل', 'التأهيل', 'التواصل', 'الفرصة', 'العميل'].map((title) => item(title, '')), signals: [item('زيارات قوية وتحويل ضعيف', 'راجع تطابق الرسالة والقيمة والثقة والاحتكاك.'), item('تحويل قوي وجودة ضعيفة', 'راجع الاستهداف والوعد والتأهيل والنية.'), item('جودة قوية وتواصل ضعيف', 'راجع التوجيه وسرعة الرد والملكية والمتابعة.'), item('تصميم قوي بلا إجراء مقاس', 'وضح الخطوة التالية والحدث الذي يجب أن يقود القرار.')], closingStatement: 'المؤشرات المفيدة تربط الانطباع والتفاعل والتحويل والتأهيل والتواصل والفرصة وتكلفة الاكتساب عندما تتوفر بيانات مبيعات موثوقة.', variant: 'measurement' },
    { __component: 'blocks.principles', eyebrow: 'لماذا إنجاز ديجيتال', heading: 'نصمم العمل كنظام، لا كمجموعة ادعاءات.', items: [item('النظام قبل العرض', 'نبحث عن البنية خلف المشكلة الظاهرة.'), item('الاستراتيجية متصلة بالتنفيذ', 'يتحول التفكير إلى تصميم وبرمجيات وحملات وربط وإجراء مقاس.'), item('تقنية ذات غرض', 'تفيد الأداة عندما توضح العملية أو تقوي القرار أو تحسن النتيجة.'), item('القياس مع الحكم', 'تدعم البيانات الفهم ولا تستبدله.'), item('مبني للتشغيل', 'يبقى العمل مفيدا بعد يوم الإطلاق.'), item('تحسين بالتغذية الراجعة', 'تصبح كل نتيجة مدخلا للقرار التالي.')] },
    { __component: 'blocks.faq', eyebrow: 'أسئلة شائعة', heading: 'بداية أوضح.', description: 'صممت المحادثة الأولى لتحديد العائق الحقيقي قبل اختيار ما يجب بناؤه.', items: [faq('ماذا تبني إنجاز ديجيتال؟', 'نبني أنظمة مواقع ونمو مترابطة توضح العرض، توجه العميل نحو الإجراء، وتجعل التحسين قابلا للقياس.'), faq('هل يجب أن أعرف الخدمة التي أحتاجها؟', 'لا. نبدأ بالهدف وموضع فقدان التقدم، ثم نقترح النظام الأنسب للبدء.'), faq('هل العمل مجرد تصميم أو تطوير؟', 'لا. التصميم والتطوير جزء من العمل، لكنهما يرتبطان بالتموضع ورحلة العميل والعمليات والقياس ونتائج الأعمال.'), faq('هل يمكن تحسين موقع أو عملية موجودة؟', 'نعم. نشخص أولا ما يعمل وما هو منفصل، ثم نحدد هل التحسين أو إعادة البناء المركزة هو القرار الأفضل.'), faq('ماذا يحدث بعد المكالمة الاستراتيجية؟', 'تحصل على توصية واضحة للخطوة التالية والنطاق المتوقع والنظام الذي يجب معالجته أولا.')] },
    { __component: 'blocks.problem', eyebrow: 'لمن هذا العمل', heading: 'للشركات المستعدة لاستبدال الجهد المتفرق بتقدم مقصود.', description: 'يناسب الشركات النامية والخدمية والاستشارية والمحلية عندما تحتاج الحالة إلى نظام أوضح.', items: [item('انتباه بلا مسار تحويل', 'الحضور موجود لكن الاهتمام بلا طريق واضح نحو الإجراء.'), item('قيمة يصعب شرحها', 'تحتاج الرسالة والتجربة أن تحملا القيمة الحقيقية.'), item('أدوات وعمليات منفصلة', 'كشف النمو فجوات في التسليم أو تكرارا أو غياب ملكية.'), item('تسويق بلا رؤية كاملة', 'يزداد الاستثمار دون وضوح بين العرض والحملة والصفحة والعميل والاستجابة.'), item('موقع لا يعكس الطموح', 'لم يعد الحضور الرقمي يدعم الثقة والإجراء والنمو.'), item('قياس قبل القرار التالي', 'يحتاج الفريق إشارات مفيدة لا مزيدا من الأرقام.')] },
    { __component: 'legacy.editorial-content', eyebrow: 'الاتجاه الأكبر', heading: 'يبدأ العمل بالنمو والمواقع، لكن الاتجاه أوسع.', body: 'النمو والمواقع هما بداية العمل. والاتجاه الأكبر هو تصميم أنظمة أوضح عبر تجربة العميل والعمليات والأتمتة واتخاذ القرار.', closingStatement: 'ليس مزيدا من التقنية لذاتها، بل بنى أفضل ينتج عبرها الإنسان والتقنية تقدما ذا معنى معا.', variant: 'vision' },
    { __component: 'blocks.final-cta', heading: 'ابدأ من المكان الذي يضيع فيه التقدم.', description: 'الخطوة الأولى ليست اختيار خدمة، بل فهم النظام والهدف والمسافة بينهما.', primaryCta: cta('ابدأ محادثة', '/book-call') },
  ],
};

const aboutAr = {
  ...aboutEn,
  title: 'عن إنجاز ديجيتال',
  seo: {
    metaTitle: 'عن إنجاز ديجيتال | من النية إلى الإنجاز',
    metaDescription: 'اكتشف معنى إنجاز ديجيتال وفلسفتها ورسالتها ورؤيتها وأساسها في التفكير بالأنظمة.',
    keywords: 'إنجاز ديجيتال, التفكير بالأنظمة, الرسالة, الرؤية, الإنجاز',
    canonicalUrl: '/about',
    noIndex: false,
  },
  blocks: [
    { __component: 'blocks.page-hero', eyebrow: 'عن إنجاز ديجيتال', title: 'نؤمن أن الإنجاز يبدأ عندما يجد الجهد اتجاهه.', description: 'إنجاز ديجيتال شركة أنظمة رقمية مبنية حول فكرة بسيطة: لا يأتي التقدم من نشاط منفصل، بل عندما تتحرك النية والناس والعمليات والتقنية والتغذية الراجعة معا.', imageKeyword: 'digital-systems-company', variant: 'visual' },
    { __component: 'legacy.editorial-content', eyebrow: 'لماذا إنجاز', heading: 'إنجاز هو الانتقال من النية إلى الواقع.', body: 'إنجاز كلمة عربية تحمل معنى التحقيق وإخراج الشيء من النية إلى الواقع.\n\nليست مجرد حركة أو نشاط، بل جهد وجد شكله واتجاهه ونتيجته.\n\nوالرقمي هو الوسط الذي تتجسد عبره هذه الفلسفة: البرمجيات والتصميم والبيانات والأتمتة والتواصل والأنظمة التي تربطها.\n\nنادرا ما تعاني الشركات الحديثة من نقص الأدوات؛ بل من غياب الانسجام. قد ينفصل الموقع عن قيمة الشركة، والإعلان عن عملية البيع، والبيانات عن القرار، وقد تخلق الأدوات عملا أكثر بدل تقليله.', closingStatement: 'توجد إنجاز ديجيتال لتجمع هذه الأجزاء في كل أوضح.', variant: 'default' },
    { __component: 'blocks.timeline', eyebrow: 'الأصل', heading: 'نقطة البداية', stages: [step('طريقة في النظر', 'بدأت إنجاز بطريقة ترى المشكلات كأجزاء من نظام أكبر لا كإخفاقات منفصلة.'), step('أساس هندسي', 'علمتنا هندسة البرمجيات تتبع التدفقات والاعتماديات والأسباب والتعقيد والتحسين بالتغذية الراجعة.'), step('إدراك', 'لا تصنع المزيد من البرمجيات والإعلانات والبيانات نتائج أفضل إلا عندما تنتمي إلى هدف واضح وعملية مترابطة.'), step('الاتجاه الحالي', 'نشأت إنجاز ديجيتال من رغبة في وصل التفكير التجاري بالتقنية والتصميم والبيانات والتنفيذ، ومنح الطموح بنية يتحول عبرها إلى إنجاز.')] },
    { __component: 'legacy.editorial-content', eyebrow: 'كيف نفكر', heading: 'المشكلة الظاهرة نادرا ما تكون المشكلة كلها.', body: 'نتعامل مع مشكلات العمل كما يتعامل المهندسون مع الأنظمة المعقدة: نفهم الكل ونفككه إلى أجزاء ذات معنى ونتتبع الحركة بينها ونجد أين تضيع النتيجة المقصودة.\n\nتحتوي الشركة على الناس والحوافز والقرارات والتواصل والعملاء والوقت والمال والعمليات والتقنية والتغذية الراجعة. يشكل الموقع الثقة، وتشكل الرسالة الطلب، وتشكل العملية سرعة الاستجابة، ويشكل المؤشر القرار، ويشكل القرار النتيجة التالية.', statements: [item('الجهد بلا اتجاه يصبح إنهاكا.', ''), item('التقنية بلا غرض تصبح تعقيدا.', ''), item('البيانات بلا حكم تصبح ضوضاء.', ''), item('الاستراتيجية بلا تنفيذ تبقى نية.', ''), item('التنفيذ بلا تغذية راجعة يكرر نفسه.', '')], closingStatement: 'يبدأ التقدم عندما تتحرك هذه العناصر كواحد.', variant: 'manifesto' },
    { __component: 'blocks.statement-pair', eyebrow: 'الرسالة والرؤية', first: { label: 'رسالتنا', statement: 'أن نحول النية إلى بنية، والجهد إلى تقدم، والقدرة الرقمية إلى إنجاز ذي معنى.', explanation: 'نجمع الاستراتيجية والتقنية والتصميم والبيانات والتنفيذ في أنظمة واضحة بما يكفي للتشغيل وذكية بما يكفي للتحسن.' }, second: { label: 'رؤيتنا', statement: 'نتصور عالما لا يترك فيه التقدم للصدفة.', explanation: 'حيث لا تصنع التقنية ضوضاء أكثر، ولا تزيد الأدوات التعقيد، ولا يضيع الجهد في أفعال منفصلة.\n\nحيث لكل هدف مسار، ولكل فعل مكان في نظام أكبر، وتصبح كل نتيجة بداية لقرار أحكم.' } },
    { __component: 'blocks.principles', eyebrow: 'المبادئ والاتجاه', heading: 'المعايير التي تبقي العمل مقصودا.', items: [item('افهم قبل أن تبني', 'يجب أن يسبق الوضوح التنفيذ.'), item('أصلح النظام لا العرض فقط', 'تبدأ المشكلات الظاهرة غالبا في مكان آخر.'), item('استخدم التقنية بقصد', 'يجب أن تحسن التقنية العمل لا أن تزينه.'), item('قس ما يوجه القرار', 'ليس كل رقم متاح جديرا بالانتباه.'), item('حسن بالتغذية الراجعة', 'يجب أن تعلم كل نتيجة ما يأتي بعدها.')], directionHeading: 'إلى أين نتجه', directionBody: 'تبدأ إنجاز ديجيتال بالأنظمة التي تلتقي عبرها الشركات بالسوق: حضورها الرقمي ومسارها لاكتساب العملاء.\n\nويمتد الاتجاه الأكبر نحو تجارب عملاء أوضح وعمليات أقوى وأتمتة ذات غرض وبنى أفضل للقرار.', closingStatement: 'الوجهة ليست مزيدا من النشاط الرقمي، بل شكلا أكثر قصدا من التقدم.' },
    { __component: 'blocks.final-cta', heading: 'يبدأ كل إنجاز كنية. وما يمنحه الواقع هو النظام المبني بينهما.', primaryCta: cta('ابدأ محادثة', '/book-call') },
  ],
};

const getJourneyPages = (locale = 'en') => {
  const source = locale === 'ar' ? arabicPages : englishPages;
  const replacements = locale === 'ar' ? [homepageAr, aboutAr] : [homepageEn, aboutEn];
  return [...source.filter((page) => page.slug !== 'home' && page.slug !== 'onboarding-engine'), ...replacements];
};

const offersEn = [
  {
    name: 'Growth Engine',
    slug: 'growth-engine',
    shortDescription: 'A connected acquisition system built around the path from market attention to qualified opportunity.',
    positioningLine: 'Growth Engine is not simply ad management. It improves the complete acquisition path, not only clicks or cheap leads.',
    outcome: 'A clearer, measurable path from attention to qualified business opportunity.',
    iconKey: 'growth-dashboard',
    capabilities: [
      item('Market and offer analysis', 'Clarify the audience, offer, acquisition strategy, and reason to respond.'),
      item('Campaign and creative system', 'Connect Meta advertising, copy, creative strategy, video scripts, and recording direction.'),
      item('Conversion path', 'Design landing pages, lead forms, WhatsApp or booking flows, and qualification.'),
      item('Integration and improvement', 'Connect Sheets or CRM, tracking, KPI analysis, and campaign optimization.'),
    ],
    flowSteps: ['Market', 'Offer', 'Message', 'Creative', 'Campaign', 'Landing Page', 'Lead', 'Analysis', 'Improvement'].map((name) => step(name, 'Connected stage in the acquisition flow.')),
    primaryCtaLabel: 'Explore Growth Engine',
    primaryCtaHref: '/growth-system',
    displayOrder: 1,
    isActive: true,
    featuredOnHomepage: true,
    seo: {
      metaTitle: 'Growth Engine | Injaaz Digital',
      metaDescription: 'A connected customer-acquisition system from market attention to qualified opportunity.',
      canonicalUrl: '/growth-system',
      noIndex: false,
    },
  },
  {
    name: 'Website Engine',
    slug: 'website-engine',
    shortDescription: 'A digital business system that communicates value, earns trust, creates action, and supports future growth.',
    positioningLine: 'Website Engine is not simply website design and development. It is business infrastructure, not an online brochure.',
    outcome: 'A maintainable digital business asset built to communicate, convert, measure, and evolve.',
    iconKey: 'website-build',
    capabilities: [
      item('Strategy and architecture', 'Connect diagnosis, sitemap, information architecture, journeys, messaging, and copy structure.'),
      item('Experience and technology', 'Deliver responsive UI/UX, reusable components, accessible development, and Strapi CMS.'),
      item('Business connections', 'Integrate forms, booking, WhatsApp, Sheets, CRM, or APIs where the journey requires them.'),
      item('Measurement and evolution', 'Establish KPI tracking, performance, technical SEO, deployment, and documentation.'),
    ],
    flowSteps: ['Strategy', 'Structure', 'Message', 'Experience', 'Technology', 'Measurement', 'Evolution'].map((name) => step(name, 'Connected stage in the website system.')),
    primaryCtaLabel: 'Explore Website Engine',
    primaryCtaHref: '/website-development',
    displayOrder: 2,
    isActive: true,
    featuredOnHomepage: true,
    seo: {
      metaTitle: 'Website Engine | Injaaz Digital',
      metaDescription: 'A strategic website system that communicates value, earns trust, creates action, and supports growth.',
      canonicalUrl: '/website-development',
      noIndex: false,
    },
  },
];

const offersAr = [
  {
    ...offersEn[0],
    name: 'محرك النمو',
    shortDescription: 'نظام اكتساب مترابط مبني حول المسار من انتباه السوق إلى فرصة مؤهلة.',
    positioningLine: 'محرك النمو ليس مجرد إدارة إعلانات، بل تحسين لمسار الاكتساب الكامل.',
    outcome: 'مسار أوضح وقابل للقياس من الانتباه إلى فرصة أعمال مؤهلة.',
    capabilities: [
      item('تحليل السوق والعرض', 'توضيح الجمهور والعرض والاستراتيجية وسبب الاستجابة.'),
      item('نظام الحملة والإبداع', 'ربط الإعلان والنص والاستراتيجية الإبداعية وتوجيه الفيديو.'),
      item('مسار التحويل', 'بناء صفحات الهبوط والنماذج وواتساب أو الحجز والتأهيل.'),
      item('الربط والتحسين', 'ربط CRM أو Sheets والتتبع والتحليل والتحسين.'),
    ],
    flowSteps: ['السوق', 'العرض', 'الرسالة', 'الإبداع', 'الحملة', 'صفحة الهبوط', 'الفرصة', 'التحليل', 'التحسين'].map((name) => step(name, 'مرحلة مترابطة في مسار الاكتساب.')),
    primaryCtaLabel: 'استكشف محرك النمو',
  },
  {
    ...offersEn[1],
    name: 'محرك الموقع',
    shortDescription: 'نظام أعمال رقمي يوضح القيمة ويبني الثقة ويخلق الإجراء ويدعم النمو المستقبلي.',
    positioningLine: 'محرك الموقع ليس مجرد تصميم وتطوير، بل بنية أعمال رقمية قابلة للتطور.',
    outcome: 'أصل رقمي قابل للإدارة والتواصل والقياس والتحسين.',
    capabilities: [
      item('الاستراتيجية والبنية', 'ربط التشخيص وخريطة الموقع وهندسة المعلومات والرحلات والرسائل.'),
      item('التجربة والتقنية', 'واجهة متجاوبة ومكونات قابلة لإعادة الاستخدام وتطوير متاح وStrapi.'),
      item('روابط العمل', 'دمج النماذج والحجز وواتساب وSheets وCRM وواجهات API حسب الحاجة.'),
      item('القياس والتطور', 'تأسيس مؤشرات الأداء والسرعة وSEO التقني والنشر والتوثيق.'),
    ],
    flowSteps: ['الاستراتيجية', 'البنية', 'الرسالة', 'التجربة', 'التقنية', 'القياس', 'التطور'].map((name) => step(name, 'مرحلة مترابطة في نظام الموقع.')),
    primaryCtaLabel: 'استكشف محرك الموقع',
  },
];

const getOffers = (locale = 'en') => locale === 'ar' ? offersAr : offersEn;

module.exports = { getJourneyPages, getOffers };
